apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
<<<<<<< HEAD
          image: thawatchai95/hello-web:sha-7c3c413b598a863d4d0c1b108eec7546627373b2
=======
          image: thawatchai95/hello-web:sha-7c3c413b598a863d4d0c1b108eec7546627373b2
>>>>>>> eb7dd4420603a07d97d0fe6cc5163632253a2d4d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10