apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
<<<<<<< HEAD
          image: thawatchai95/hello-web:sha-40c3b6512bdc1edb7fa064f72e7c3e787a2c94cf
=======
          image: thawatchai95/hello-web:sha-40c3b6512bdc1edb7fa064f72e7c3e787a2c94cf
>>>>>>> eb7dd4420603a07d97d0fe6cc5163632253a2d4d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10